<fluent-page header="Articles">
    <?php $index = -1; ?>
    <script type="text/javascript" src="../../js/article.js"></script>
    <script type="text/javascript">document.querySelector("#menu-item-articles").setAttribute("selected", ""); let contentHTML;</script>
    <?php foreach (loadLastArticles($db, 10) as $article) { 
        $index++;
        require("../controls/articleControl.php");
    } 
    if ($index == -1) { ?>
        <p>There are currently no articles. <?php if (isset($_SESSION["user"])) { ?> <fluent-hyperlink href="./createArticle.php">Try to contribute and write one!</fluent-hyperlink> <?php } ?> </p>
    <?php } ?>
</fluent-page>