<fluent-page header="Create article">
    <script type="text/javascript">document.querySelector("#menu-item-create-article").setAttribute("selected", "");</script>
    <form method="POST" style="padding: 0; border: none; margin-right: 5em;">
        <input style="width: 100%;" placeholder="Title" type="text" name="title" id="title" required>
        <textarea name="content" placeholder="Article's content in Markdown" id="content" style="resize: none; width: 100%; min-height: 15em;"></textarea>
        <button accent>Publish</button>
    </form>
</fluent-page>