<fluent-page header="Sign up">
    <script type="text/javascript">document.querySelector("#menu-item-sign-up").setAttribute("selected", "");</script>
    <form method="POST" style="padding: 0; border: none;">
        <input placeholder="Username" type="text" name="username" id="username" required><br>
        <input placeholder="E-Mail" type="email" name="email" id="email" required><br>
        <input showpass_btn placeholder="Password" type="password" name="password" id="password" required><br>
        <input type="submit" value="Sign up">
    </form>
</fluent-page>