<fluent-page header="Sign in">
    <script type="text/javascript">document.querySelector("#menu-item-sign-in").setAttribute("selected", "");</script>
    <form method="POST" style="padding: 0; border: none;">
        <input placeholder="E-Mail" type="email" name="email" id="email" required><br>
        <input showpass_btn placeholder="Password" type="password" name="password" id="password" required><br>
        <input type="submit" value="Sign in">
    </form>
</fluent-page>