            
                </fluent-page-switcher>
            </fluent-main-content>
        </fluent-web-container>
    </body>
    <footer>
        <script type="text/javascript" src="https://resources.bexcool.eu/fluentwebframework/src/js/fluent_elements.min.js"></script>
        <script type="text/javascript" src="https://resources.bexcool.eu/fluentwebframework/src/js/fluent_functions.min.js"></script>
        <script type="text/javascript">
            initUserSession();
            document.getElementById("user-profile-header").innerHTML = "LOOOL";
            setTimeout(() => { EnableMica(); SetDarkTheme(); }, 100);
        </script>
    </footer>
</html>