            
                </fluent-page-switcher>
            </fluent-main-content>
        </fluent-web-container>
    </body>
    <footer>
        <script type="text/javascript" src="https://resources.bexcool.eu/fluentwebframework/src/js/fluent_functions.min.js"></script>
        <script type="text/javascript">setTimeout(() => { DisableMica(); SetDarkTheme(); }, 100);</script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    </footer>
</html>